version: 0.2

phases:
  install:
    commands:
      - npm install # Install dependencies
  build:
    commands:
      - echo "Skipping build step since it's not needed."
  post_build:
    commands:
      - echo "Creating a zip file of the project..."
      - zip -r my-nodejs-app.zip * # Zip the entire project including node_modules
      - echo "Zip file created successfully."

artifacts:
  files:
    - my-nodejs-app.zip # Include the zip file as a build artifact
